EscritorioAdvocacia/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace EscritorioAdvocacia.Models {
    public class Cliente {
        public string Nome { get; set; }
        [Key]
        public int Id { get; set; }
        public string Cnpj { get; set; }
        public string Estado { get; set; }
        public ICollection<Processo> Processos { get; set; } = new List<Processo>();

        public Cliente() {
        }

        public Cliente(int id, string nome, string cnpj, string estado) {
            Id = id;
            Nome = nome;
            Cnpj = cnpj;
            Estado = estado;
        }
    }
}

EscritorioAdvocacia/Models/ErrorViewModel.cs
using System;

namespace EscritorioAdvocacia.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EscritorioAdvocacia/Models/Processo.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace EscritorioAdvocacia.Models {
    public class Processo {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Número do Processo")]
        public string Numero { get; set; }
        public string Estado { get; set; }       
        public string Status { get; set; }
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:F2}")]
        public double Valor { get; set; }
        [Display(Name = "Data de Criação")]
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        public Cliente  Cliente { get; set; }

        [Display(Name = "Cliente")]
        public int ClienteId { get; set; }

        public Processo() {

        }
        public Processo(int id, string numero, string estado, string status, double valor, DateTime data, Cliente cliente) {
            Id = id;
            Numero = numero;
            Estado = estado;
            Status = status;
            Valor = valor;
            Data = data;
            Cliente = cliente;
        }

       
    }
}

EscritorioAdvocacia/Models/ViewModels/ProcessoFormViewModel.cs
using System.Collections.Generic;

namespace EscritorioAdvocacia.Models.ViewModels {
    public class ProcessoFormViewModel {
        public Processo Processo { get; set; }
        public ICollection<Cliente> Clientes { get; set; }
    }
}

EscritorioAdvocacia/Controllers/ClientesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EscritorioAdvocacia.Models;
using EscritorioAdvocacia.Services;

namespace EscritorioAdvocacia.Controllers
{
    public class ClientesController : Controller
    {
        private readonly EscritorioAdvocaciaContext _context;

        public ClientesController(EscritorioAdvocaciaContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public IActionResult Index()
        {
            var clienteServce = new ClienteService(_context);
            var list = clienteServce.FindAll();
            return View(list);
        }


        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Cnpj,Estado")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }
    }
}

EscritorioAdvocacia/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace EscritorioAdvocacia.Controllers {
    public class HomeController : Controller {
        public IActionResult Index() {
            return View();
        }

        public IActionResult About() {
            ViewData["Message"] = "Sistema para Escritório de Advocacia.";

            return View();
        }

        public IActionResult Contact() {

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new EscritorioAdvocacia.Models.ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EscritorioAdvocacia/Controllers/ProcessosController.cs
using Microsoft.AspNetCore.Mvc;
using EscritorioAdvocacia.Models;
using EscritorioAdvocacia.Models.ViewModels;
using EscritorioAdvocacia.Services;

namespace EscritorioAdvocacia.Controllers {
    public class ProcessosController : Controller {
        private readonly ProcessoService _processoService;
        private readonly ClienteService _clienteService;
        public ProcessosController(ProcessoService processoService, ClienteService clienteService) {
            _processoService = processoService;
            _clienteService = clienteService;
        }

        public IActionResult Index() {
            var list = _processoService.FindAll();
            return View(list);
        }

        public IActionResult Create() {
            var clientes = _clienteService.FindAll();
            var viewModel = new ProcessoFormViewModel { Clientes = clientes };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Processo processo) {
            _processoService.Insert(processo);
            return RedirectToAction(nameof(Index));

        }
    }
}

EscritorioAdvocacia/Views/Clientes/Create.cshtml
@model EscritorioAdvocacia.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" class="form-control" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volta para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EscritorioAdvocacia/Views/Clientes/Index.cshtml
@model IEnumerable<EscritorioAdvocacia.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Criar Novo Cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cnpj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>

        </tr>
}
    </tbody>
</table>

EscritorioAdvocacia/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Sistema de Gerenciamento de Processos.</p>

EscritorioAdvocacia/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<address>
    <strong>Nome:</strong> Debora Stuck<br />
    <strong>Celular:</strong> (21) 98771-5084<br/>
    <strong>E-mail:</strong> <a href="mailto:deborastuck@gmail.com">deborastuck@gmail.com</a><br/>
    <strong>Linkedin:</strong> <a href="http://www.linkedin.com/in/deborastuck">www.linkedin.com/in/deborastuck</a>
</address>

EscritorioAdvocacia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    <div class="col-md-6">
        <h2>Gerenciamento de Processos</h2>
        <ul>
            <li>Lorem Ipsum is simply dummy text of the printing and typesetting </li>
            <li>Lorem Ipsum has been the industry's standard dummy </li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>Como Usar o Sistema</h2>
        <ul>
            <li>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout</li>
            <li>Many desktop publishing packages and web page editors now use Lorem Ipsum</li>
            <li>Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</li>
        </ul>
    </div>
</div>

EscritorioAdvocacia/Views/Processos/Create.cshtml
@model EscritorioAdvocacia.Models.ViewModels.ProcessoFormViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>@ViewData["Title"]</h2>

<h4>Processos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Processo.Numero" class="control-label"></label>
                <input asp-for="Processo.Numero" class="form-control" />
                <span asp-validation-for="Processo.Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo.Estado" class="control-label"></label>
                <input asp-for="Processo.Estado" class="form-control" />
                <span asp-validation-for="Processo.Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo.Status" class="control-label"></label>
                <select asp-for="Processo.Status" class="form-control">
                        <option value="ativo">Ativo</option>
                        <option value="inativo">Inativo</option> 
                </select>
                <span asp-validation-for="Processo.Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo.Valor" class="control-label"></label>
                <input asp-for="Processo.Valor" class="form-control" />
                <span asp-validation-for="Processo.Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo.Data" class="control-label"></label>
                <input asp-for="Processo.Data" class="form-control" />
                <span asp-validation-for="Processo.Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo.ClienteId" class="control-label"></label>
                <select asp-for="Processo.ClienteId" asp-items="@(new SelectList(Model.Clientes, "Id", "Nome"))" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EscritorioAdvocacia/Views/Processos/Index.cshtml
@model IEnumerable<EscritorioAdvocacia.Models.Processo>

@{
    ViewData["Title"] = "Processos";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Create">Criar Novo Processo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
        </tr>
}
    </tbody>
</table>

EscritorioAdvocacia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EscritorioAdvocacia</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EscritorioAdvocacia</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
                    <li><a asp-area="" asp-controller="Processos" asp-action="Index">Processos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EscritorioAdvocacia</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>